name: Autobuild

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  prettier:
    name: Automated prettier
    uses: ./.github/workflows/prettier.yml
    secrets: inherit

  build:
    needs: prettier
    name: Autobuild

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - uses: actions/setup-python@v2

      - name: Get QT From Cache
        id: cache-qt
        uses: actions/cache/restore@v3
        with:
          path: C:\Qt
          key: ${{ runner.os }}-Qt563

      - name: Download Qt if Needed
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          mkdir C:\Qt
          python resources\qt_download_helper.py
          cd C:\Qt
          7z x qt563.7z

      - name: Save Qt to cache
        if: steps.cache-qt.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: C:\Qt
          key: ${{ runner.os }}-Qt563

      - name: Get prettier result
        uses: actions/download-artifact@v4
        with:
          name: json
          path: resources
        continue-on-error: true

      - name: Build
        run: |
          mkdir C:\spelunky2-x64dbg-plugin-autobuild
          mkdir build
          cd build
          cmake .. -DX64DBG_PLUGINS_ROOT=C:\spelunky2-x64dbg-plugin-autobuild -DQt5_DIR=C:\Qt\5.6.3\msvc2013_64\lib\cmake\Qt5\
          cmake --build . --config Release --target ALL_BUILD

      - name: Pack build files
        run: 7z a -tzip spelunky2-x64dbg-plugin-autobuild.zip C:\spelunky2-x64dbg-plugin-autobuild\

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: false
          title: "Autobuild"
          files: |
             spelunky2-x64dbg-plugin-autobuild.zip
