name: Clang-Format Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      do_formatting:
        description: "Run clang-format inplace formatting and commit the result"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.do_formatting != 'true' }}
        with:
          source: "src include"
          extensions: "inl,h,hpp,cpp"
          clangFormatVersion: 16

      - uses: DoozyX/clang-format-lint-action@v0.16.2
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.do_formatting == 'true' }}
        with:
          source: "src include"
          extensions: "inl,h,hpp,cpp"
          clangFormatVersion: 16
          inplace: true
      - uses: EndBug/add-and-commit@v4
        if: ${{ success() && github.event_name == 'workflow_dispatch' && github.event.inputs.do_formatting == 'true' }}
        with:
          author_name: Clang-Format Bot
          author_email: fake.user@github.com
          message: "Automated clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
